### ISSUE TITLE
The "windows-2012" image does not exist on Hashicorp's cloud.

### ISSUE THREAD

**Issue by p0six** [learn-chef/learn_chef_iis#5]
This repo is referenced from the following tutorial: https://learn.chef.io/modules/local-development/windows/virtualbox/apply-a-cookbook#/

The windows image referenced by this particular cookbook is no longer available.

**Comment by tpetchel** [comment]
Hi @p0six - Hashicorp never provided this image. The name you see refers to a Windows box you need to build locally. See the [previous page](https://learn.chef.io/modules/local-development/windows/virtualbox/get-set-up#/) for details.

**Comment by p0six** [comment]
@tpetchel apologies.  Thanks for the quick response!
